#!/bin/sh

echo "Running tests before commit..."

yarn test --passWithNoTests

if [ $? -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "All tests passed. Proceeding with commit."
