import {
  Alert, AlertTitle, Fade,
  Stack,
  useTheme,
} from '@mui/material';
import TrapFocus from '@mui/material/Unstable_TrapFocus';
import React from 'react';

export const DisclaimerComponent = () => {
  const [bannerOpen, setBannerOpen] = React.useState(true);

  const theme = useTheme();

  const closeBanner = () => {
    setBannerOpen(false);
  };

  return (
    <Fade appear={true} in={bannerOpen}>

      <Stack
        direction={{
          xs: 'column',
          sm: 'row',
        }}
        sx={{
          position: 'fixed',
          bottom: 0,
          left: 0,
          right: 0,

        }}
      >
        <Alert
          variant="filled"
          sx={{
            opacity: 0.90,
            backgroundColor: theme.palette.info.main,
            color: theme.palette.text.primary,
          }}
          onClose={closeBanner}
          icon="⚠️"
        >
          <AlertTitle>Experimental Project - AI-Generated Content:</AlertTitle>
          This is an experimental tool developed with AI assistance.
          All scoring algorithms and investment strategies were generated by AI and may not be reliable.
          <strong> This is NOT financial advice.</strong> For educational purposes only. Always consult qualified financial professionals before making investment decisions.
        </Alert>
      </Stack>

    </Fade>
  );
};
