
export const COMMON_LABELS = {
  RiskLevel: 'Risk Level',
  StaticValue: 'This value requires manual update. Last updated on ',
  StrongBullish: 'STRONG BULLISH',
  Bullish: 'BULLISH',
  CrabMarket: 'CRAB MARKET',
  Bearish: 'BEARISH',
  StrongBearish: 'STRONG BEARISH',
  StrongBuy: 'STRONG BUY',
  Buy: 'BUY',
  ModerateBuy: 'MODERATE BUY',
  Neutral: 'NEUTRAL',
  ModerateSell: 'MODERATE SELL',
  Sell: 'SELL',
  StrongSell: 'STRONG SELL',
  Inflows: 'INFLOWS',
  Outflows: 'OUTFLOWS',
  FlightToSafety: 'FLIGHT TO SAFETY',
  Accumulation: 'ACCUMULATION',
  StrongInflows: 'STRONG INFLOWS',
  VeryLowRisk: '🚀 VERY LOW RISK',
  LowRisk: '🟢 LOW RISK',
  ModerateRisk: '🟡 MODERATE RISK',
  HighRisk: '🔴 HIGH RISK',
  Critical: '💥 CRITICAL',
};

export const CRYPTO_LABELS = {
  BtcFearGreed: 'BTC Fear & Greed',
  BtcFearGreedDescription: 'Market sentiment indicator combining volatility, momentum, social media and surveys. Extreme Fear (<25) often presents buying opportunities, Extreme Greed (>75) suggests caution.',
  BtcRsi: 'BTC RSI',
  BtcRsiDescription: 'Relative Strength Index (14-day) measures momentum. Values above 70 indicate overbought conditions (potential correction), while below 30 suggests oversold (potential buying opportunity).',
  BtcDominance: 'BTC Dominance',
  BtcDominanceDescription: 'Bitcoin market share relative to total crypto market cap. Higher dominance (>60%) indicates capital flowing into BTC, while lower values (<50%) suggest altcoin season.',
  AltSeasonIndex: 'Alt Season Index',
  AltSeasonIndexDescription: 'Measures altcoin performance vs Bitcoin. Values above 75 indicate strong altcoin season, while below 25 shows Bitcoin outperformance. Based on top altcoins vs BTC performance.',
  AthDistance: 'ATH Distance',
  AthDistanceDescription: 'Shows how far Bitcoin is from its all-time high peak. Values above 95% indicate near ATH (high risk zone), while lower values suggest better risk/reward ratio for accumulation.',
  Momentum7D: 'Momentum 7D',
  Momentum7DDescription: '7-day price momentum showing short-term trend strength. Positive values indicate upward momentum, negative values show downward pressure. Helps identify trend reversals.',
  Strategy: '₿ Crypto Strategy',
  MarketPhase: 'Market Phase',
  TimeHorizon: 'Time Horizon',
  BtcAltcoin: 'BTC vs Altcoins',
  PortfolioBalance: 'Portfolio Balance',
  RiskManagement: 'Risk Management',
  KeyMetric: 'Key Metric',
  ActionItems: 'Action Items',
  OverallScore: 'Crypto Overall Score',
  Description: 'Overall cryptocurrency market sentiment combining Bitcoin metrics, dominance, RSI, and Fear & Greed indicators.',
};

export const STOCKS_LABELS = {
  Vix: 'VIX',
  VixDescription: 'CBOE Volatility Index measuring market fear and uncertainty. Values below 15 indicate calm markets, 15-25 show normal volatility, above 30 signals high stress and potential market corrections.',
  RsiSP500: 'RSI S&P 500',
  RsiSP500Description: 'S&P 500 Relative Strength Index (14-day) measuring momentum. Above 70 indicates overbought conditions (potential pullback), below 30 shows oversold (potential rebound opportunity).',
  EurUsd: 'EUR/USD',
  EurUsdDescription: 'EUR/USD exchange rate indicating relative strength between Eurozone and US economies. Higher values favor European stocks, lower values benefit US exporters and dollar-denominated assets.',
  FearGreed: 'Fear & Greed',
  FearGreedDescription: 'CNN Fear & Greed Index combining market momentum, volatility, put/call ratios, and breadth. Extreme Fear (<25) often signals buying opportunities, Extreme Greed (>75) suggests caution.',
  AthDistance: 'ATH Distance',
  AthDistanceDescription: 'S&P 500 distance from all-time high. Values above 95% indicate near peak levels (elevated risk), while lower values suggest better risk/reward ratio and accumulation opportunities.',
  Momentum7D: 'Momentum 7D',
  Momentum7DDescription: 'S&P 500 7-day momentum measuring short-term trend strength. Positive values indicate bullish momentum, negative values show bearish pressure. Helps identify potential trend changes.',
  OverallScore: 'Stocks Overall Score',
  PortfolioStrategy: 'Portfolio Strategy',
  SectorFocus: 'Sector Focus',
  RiskManagement: 'Risk Management',
  ActionItems: 'Action Items',
  MarketPhase: 'Market Phase',
  TimeHorizon: 'Time Horizon',
  Allocation: 'Allocation',
  RecommendedSectors: 'Recommended Sectors',
  KeyMetric: 'Key Metric',
  MarketVolatilityMeasure: 'Market volatility measure',
  OverboughtOversold: 'Overbought/Oversold Indicator',
  CurrencyStrength: 'Currency Strength',
  SentimentIndicator: 'Sentiment Indicator',
  EconomicStability: 'Economic Stability',
  RiskLevel: 'Risk Level',
  Description: 'Overall stock market sentiment combining S&P 500 metrics, VIX volatility, RSI, and Fear & Greed indicators.',
};

export const AI_BUBBLE_LABELS = {
  title: 'AI Bubble Indicator',
  subtitle: 'Early warning system for AI sector correction',
  nvidiaPE: 'NVIDIA P/E Ratio',
  nvidiaPEDescription: 'NVIDIA Price-to-Earnings ratio as AI sector valuation proxy. Historical avg ~40-60. Values above 80 indicate expensive valuations and potential bubble risk in AI stocks.',
  nasdaqPE: 'NASDAQ 100 P/E',
  nasdaqPEDescription: 'NASDAQ 100 Price-to-Earnings ratio measuring tech sector valuation. Historical avg ~25-30. Values above 35 suggest stretched valuations and elevated market risk.',
  vixPersistence: 'VIX Persistence',
  vixPersistenceDescription: 'Number of days VIX stayed above 30 (high fear) in the last 5 days. Sustained high volatility signals market stress, potential correction or bubble deflation phase.',
  nvdaNasdaqRatio: 'NVDA/NASDAQ Ratio',
  nvdaNasdaqRatioDescription: 'NVIDIA PE / NASDAQ PE ratio showing AI sector premium over broader tech. Ratio above 2.0 indicates AI stocks trading at significant premium, suggesting sector-specific bubble risk.',
  fearGreed: 'Fear & Greed',
  fearGreedDescription: 'Market sentiment combining volatility, momentum, and put/call ratios. Extreme Greed (>75) combined with high valuations suggests euphoric phase and bubble risk.',
  rsiSP500: 'RSI S&P 500',
  rsiSP500Description: 'S&P 500 Relative Strength Index (14-day). Values above 70 indicate overbought conditions. Combined with elevated valuations, suggests increased probability of market correction.',
  riskLevel: 'Bubble Risk',
  factors: 'Active Factors',
  portfolioAction: '💼 Portfolio Action',
  sectorRotation: 'Sector Rotation',
  timingStrategy: 'Timing Strategy',
  actionableTips: 'Actionable Tips',
  recommendation: 'Recommendation',
  recommendedSectors: 'Recommended Sectors',
  action: 'Action',
  OverallScore: 'AI Bubble Risk Score',
  OverallScoreDescription: 'AI sector bubble risk assessment based on tech valuations (NVIDIA, NASDAQ), market sentiment (Fear & Greed, RSI), and volatility patterns (VIX).',
};

export const TREASURY_BONDS_LABELS = {
  Yield10Y: '10Y Treasury',
  Yield10YDescription: '10-year US Treasury yield, benchmark for long-term rates. Higher yields (>4.5%) make bonds attractive vs stocks, lower yields (<3%) favor equities. Reflects long-term economic outlook.',
  Yield5Y: '5Y Treasury',
  Yield5YDescription: '5-year Treasury yield, mid-term rate indicator. Used for mortgage pricing and medium-duration bonds. Rising yields signal tightening conditions, falling yields suggest easing ahead.',
  Yield2Y: '2Y Treasury',
  Yield2YDescription: '2-year Treasury yield, sensitive to Fed policy. Closely tracks federal funds rate expectations. Rising 2Y yields indicate expected Fed tightening, falling suggests rate cuts ahead.',
  YieldCurveSlope: 'Yield Curve',
  YieldCurveSlopeDescription: 'Yield curve slope (10Y - 2Y). Positive slope indicates healthy economy, negative (inverted) historically precedes recessions. Steepening favors long-duration bonds.',
  CreditSpreads: 'Credit Spreads',
  CreditSpreadsDescription: 'Corporate bond spread over Treasuries in basis points. Widening spreads (>200 bps) indicate credit stress and flight to quality. Tight spreads (<100 bps) show investor confidence.',
  Inflation: 'Inflation',
  InflationDescription: 'Expected inflation rate from market-implied indicators. Higher inflation (>3%) erodes bond returns and favors TIPS. Lower inflation (<2%) benefits nominal bonds.',
  OverallScore: 'Treasury Bonds Score',
  OverallScoreDescription: 'Overall treasury bonds sentiment based on yield curves, spreads, and economic indicators',
  DurationStrategy: 'Duration Strategy',
  AllocationStrategy: 'Allocation Strategy',
  RiskAssessment: 'Risk Assessment',
  ActionItems: 'Action Items',
};

export const CAPITAL_FLOWS_LABELS = {
  FedBalanceSheet: 'Fed Balance Sheet',
  FedBalanceSheetDescription: 'Federal Reserve total assets. Expanding balance sheet (QE) injects liquidity into markets, bullish for risk assets. Contracting (QT) removes liquidity, bearish signal.',
  M2MoneySupply: 'M2 Money Supply',
  M2MoneySupplyDescription: 'M2 money supply measures total money in circulation. Growing M2 indicates increasing liquidity (bullish), while contraction suggests monetary tightening (bearish).',
  DollarIndex: 'US Dollar Index',
  DollarIndexDescription: 'US Dollar strength index. Weak dollar (falling) is bullish for risk assets like crypto and stocks. Strong dollar (rising) indicates flight to safety, bearish for risk.',
  HighYieldSpread: 'High Yield Spread',
  HighYieldSpreadDescription: 'High yield bond spread measures risk premium. Narrow spreads (<4%) indicate high risk appetite (bullish). Wide spreads (>7%) show risk aversion (bearish).',
  Treasury10Y: '10Y Treasury Yield',
  Treasury10YDescription: '10-Year Treasury yield trend as safe haven indicator. Falling yields = flight to bonds/safety (bearish for risk). Rising yields = capital leaving bonds (bullish for risk).',
  StablecoinAccumulation: 'Stablecoin Reserves',
  StablecoinAccumulationDescription: 'Stablecoin supply as % of total crypto market cap. High dominance (>6%) indicates dry powder ready to deploy (very bullish). Low (<3%) means money already deployed.',
  CryptoMarketCap: 'Crypto Market Cap',
  CryptoMarketCapDescription: 'Total crypto market cap growth. Rapid growth (>10% in 4 weeks) shows strong capital inflows (bullish). Decline (<-10%) indicates capital flight (bearish).',
  OverallScore: 'Capital Flows Score',
  Description:
    'Market sentiment based on capital flows, liquidity conditions, stablecoin accumulation, and institutional positioning across stocks, crypto, and safe haven assets.',
  MarketSentimentPhase: 'Market Sentiment Phase',
  LiquidityConditions: 'Liquidity Conditions',
  RiskAppetite: 'Risk Appetite',
  AssetAllocation: 'Recommended Allocation',
  TimeHorizon: 'Time Horizon',
  ActionItems: 'Action Items',
  KeyMetric: 'Key Metric',
};
