
export const COMMON_LABELS = {
  RiskLevel: 'Risk Level',
};

export const CRYPTO_LABELS = {
  BtcFearGreed: 'BTC Fear & Greed',
  BtcRsi: 'BTC RSI',
  BtcDominance: 'BTC Dominance',
  AltSeasonIndex: 'Alt Season Index',
  AthDistance: 'ATH Distance',
  Momentum7D: 'Momentum 7D',
  Strategy: '₿ Crypto Strategy',
  MarketPhase: 'Market Phase',
  TimeHorizon: 'Time Horizon',
  BtcAltcoin: 'BTC vs Altcoins',
  PortfolioBalance: 'Portfolio Balance',
  RiskManagement: 'Risk Management',
  KeyMetric: 'Key Metric',
  ActionItems: 'Action Items',
  OverallScore: 'Crypto Overall Score',
  Description: 'Overall cryptocurrency market sentiment combining Bitcoin metrics, dominance, RSI, and Fear & Greed indicators.',
};

export const STOCKS_LABELS = {
  Vix: 'VIX',
  RsiSP500: 'RSI S&P 500',
  EurUsd: 'EUR/USD',
  FearGreed: 'Fear & Greed',
  AthDistance: 'ATH Distance',
  Momentum7D: 'Momentum 7D',
  OverallScore: 'Stocks Overall Score',
  PortfolioStrategy: 'Portfolio Strategy',
  SectorFocus: 'Sector Focus',
  RiskManagement: 'Risk Management',
  ActionItems: 'Action Items',
  MarketPhase: 'Market Phase',
  TimeHorizon: 'Time Horizon',
  Allocation: 'Allocation',
  RecommendedSectors: 'Recommended Sectors',
  KeyMetric: 'Key Metric',
  MarketVolatilityMeasure: 'Market volatility measure',
  OverboughtOversold: 'Overbought/Oversold Indicator',
  CurrencyStrength: 'Currency Strength',
  SentimentIndicator: 'Sentiment Indicator',
  EconomicStability: 'Economic Stability',
  RiskLevel: 'Risk Level',
  Description: 'Overall stock market sentiment combining S&P 500 metrics, VIX volatility, RSI, and Fear & Greed indicators.',
};

export const AI_BUBBLE_LABELS = {
  title: 'AI Bubble Indicator',
  subtitle: 'Early warning system for AI sector correction',
  nvidiaPE: 'NVIDIA P/E Ratio',
  nasdaqPE: 'NASDAQ 100 P/E',
  vixPersistence: 'VIX Persistence',
  nvdaNasdaqRatio: 'NVDA/NASDAQ Ratio',
  fearGreed: 'Fear & Greed',
  rsiSP500: 'RSI S&P 500',
  riskLevel: 'Bubble Risk',
  factors: 'Active Factors',
  portfolioAction: '💼 Portfolio Action',
  sectorRotation: 'Sector Rotation',
  timingStrategy: 'Timing Strategy',
  actionableTips: 'Actionable Tips',
  recommendation: 'Recommendation',
  recommendedSectors: 'Recommended Sectors',
  action: 'Action',
  OverallScore: 'AI Bubble Risk Score',
};

export const TREASURY_BONDS_LABELS = {
  Yield10Y: '10Y Treasury',
  Yield5Y: '5Y Treasury',
  Yield2Y: '2Y Treasury',
  YieldCurveSlope: 'Yield Curve',
  CreditSpreads: 'Credit Spreads',
  Inflation: 'Inflation',
  OverallScore: 'Treasury Bonds Score',
  DurationStrategy: 'Duration Strategy',
  AllocationStrategy: 'Allocation Strategy',
  RiskAssessment: 'Risk Assessment',
  ActionItems: 'Action Items',
};
