name: Deploy React App to Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          
      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@4.9.4 --activate
          yarn --version
          
      - name: Install dependencies
        run: yarn install --immutable
        
      - name: Build React app
        run: yarn build
        
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/956703426361/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-firebase@cristian-giuliani.iam.gserviceaccount.com'
          
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install Functions dependencies
        run: npm install --prefix functions

      - name: Build Functions
        run: npm run build --prefix functions
      
      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
        
      - name: Deploy to Firebase Hosting
        run: firebase deploy --project cristian-giuliani --only hosting:scorecards
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ steps.auth.outputs.credentials_file_path }}
          GCLOUD_PROJECT: cristian-giuliani